import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
type Variant={color?:string|null;size?:string|null;cost?:number|string|null;sku?:string|null};
function money(cost:Variant["cost"]){const base=Math.max(0,Number(cost)||0),target=Math.max(base*2.2,base+15,24);return(Math.ceil(target)-.01).toFixed(2)}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{headers:cors});try{const authHeader=req.headers.get("Authorization");if(!authHeader)throw new Error("Sign in required");const authClient=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:authHeader}}});const{data:{user},error:authError}=await authClient.auth.getUser();if(authError||!user)throw new Error("Invalid or expired sign-in");
const domain=(Deno.env.get("SHOPIFY_STORE_DOMAIN")||"").replace(/^https?:\/\//,"").replace(/\/$/,""),token=Deno.env.get("SHOPIFY_ADMIN_ACCESS_TOKEN");if(!domain||!token)throw new Error("Shopify is not connected yet. Add SHOPIFY_STORE_DOMAIN and SHOPIFY_ADMIN_ACCESS_TOKEN to Supabase Edge Function secrets.");
const{title,mockup_url,placement,variants=[]}=await req.json();if(!title||!mockup_url||!Array.isArray(variants)||!variants.length)throw new Error("Product title, approved mockup, and at least one variant are required");const cleanTitle=String(title).trim().slice(0,255);const story=`<p><strong>${cleanTitle}</strong> turns original artwork into something made to live with—not just something to look at.</p><p>Created through Frontline’s artist-led process, this piece carries the energy of handmade work while being produced on demand to reduce waste. The ${String(placement||"front").replaceAll("_"," ")} placement keeps the design intentional.</p><p>Made to order. Please review the selected size and color before checkout.</p>`;
const colors=[...new Set(variants.map((v:Variant)=>v.color).filter(Boolean))]as string[],sizes=[...new Set(variants.map((v:Variant)=>v.size).filter(Boolean))]as string[],options=[]as{name:string;values:{name:string}[]}[];if(colors.length)options.push({name:"Color",values:colors.map(name=>({name}))});if(sizes.length)options.push({name:"Size",values:sizes.map(name=>({name}))});if(!options.length)options.push({name:"Style",values:[{name:"Standard"}]});const productVariants=variants.map((v:Variant)=>({price:Number(money(v.cost)),optionValues:options.map(o=>({optionName:o.name,name:o.name==="Color"?(v.color||colors[0]):o.name==="Size"?(v.size||sizes[0]):"Standard"}))}));
const query=`mutation CreateDraft($input: ProductSetInput!) { productSet(synchronous: true, input: $input) { product { id title status } userErrors { field message } } }`;
const input={title:cleanTitle,descriptionHtml:story,status:"DRAFT",vendor:"Frontline",productType:"Artist Designed",productOptions:options,variants:productVariants,files:[{originalSource:mockup_url,alt:`${cleanTitle} product mockup`,contentType:"IMAGE"}]};
const response=await fetch(`https://${domain}/admin/api/2026-07/graphql.json`,{method:"POST",headers:{"X-Shopify-Access-Token":token,"Content-Type":"application/json"},body:JSON.stringify({query,variables:{input}})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.errors?JSON.stringify(data.errors):`Shopify returned ${response.status}`);if(data.errors?.length)throw new Error(data.errors.map((e:{message:string})=>e.message).join("; "));const errors=data.data?.productSet?.userErrors||[];if(errors.length)throw new Error(errors.map((e:{message:string})=>e.message).join("; "));const product=data.data?.productSet?.product;if(!product)throw new Error("Shopify did not return the created draft");const numericId=String(product.id).split("/").pop();return Response.json({product:{id:product.id,title:product.title,status:product.status,admin_url:`https://${domain}/admin/products/${numericId}`}},{headers:cors})}catch(e){return Response.json({error:(e as Error).message},{status:400,headers:cors})}});
