import { useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "./supabase";

type Store={id:number;name:string;type:string}; type Product={id:string;name:string;color:string|null;size:string|null;thumbnail_url:string|null;sync_data:any};
type Result={url:string;product:string;placement:string}; type DesignAsset={id:string;name:string;url:string;source:"upload"|"link"};
const productRoles=["Baby / onesie","Kids","Mom","Dad","Family matching","Accessory"];
async function callPrintful(path:string,method="GET",payload?:unknown,params?:Record<string,string>,storeId?:number){const{data,error}=await supabase.functions.invoke("printful",{body:{path,method,payload,params,store_id:storeId}});if(error)throw error;if(data?.error)throw new Error(data.error);return data?.data?.result??data?.data}
async function createShopifyDraft(payload:Record<string,unknown>){const{data,error}=await supabase.functions.invoke("shopify-draft",{body:payload});if(error)throw error;if(data?.error)throw new Error(data.error);return data.product}

export default function App(){
 const[session,setSession]=useState<Session|null>(null),[authReady,setAuthReady]=useState(false);const[email,setEmail]=useState(""),[password,setPassword]=useState("");const[stores,setStores]=useState<Store[]>([]),[products,setProducts]=useState<Product[]>([]);const[storeId,setStoreId]=useState<number>(),[productId,setProductId]=useState("");const[placement,setPlacement]=useState("front"),[assets,setAssets]=useState<DesignAsset[]>([]),[activeAssetId,setActiveAssetId]=useState(""),[imageLink,setImageLink]=useState("");
 const[collectionName,setCollectionName]=useState("Forging Hammahs"),[productRole,setProductRole]=useState("Baby / onesie"),[designDirection,setDesignDirection]=useState("Matching island-workwear artwork for babies, kids, moms, and dads. Keep the hammer, Menehune-made seal, cream/teal/black palette, and a warm family connection across the set.");const[busy,setBusy]=useState(false),[message,setMessage]=useState("Checking Printful…");const[result,setResult]=useState<Result|null>(null);
 const product=useMemo(()=>products.find(p=>p.id===productId),[products,productId]),activeAsset=useMemo(()=>assets.find(a=>a.id===activeAssetId),[assets,activeAssetId]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session)return;(async()=>{try{const s=await callPrintful("/stores");setStores(s||[]);setStoreId(s?.[0]?.id);const{data,error}=await supabase.from("printful_products").select("*").order("name");if(error)throw error;setProducts(data||[]);setMessage("Connected — build a collection, then choose a product.")}catch(e:any){setMessage(e.message||"Connection failed")}})()},[session]);
 async function signIn(){setBusy(true);const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message);setBusy(false)}
 async function uploadFiles(files:FileList){setBusy(true);setMessage(`Adding ${files.length} reference image${files.length===1?"":"s"}…`);try{const added:DesignAsset[]=[];for(const file of Array.from(files)){const path=`designs/${crypto.randomUUID()}-${file.name}`;const{error}=await supabase.storage.from("printful-designs").upload(path,file,{contentType:file.type});if(error)throw error;const{data,error:signError}=await supabase.storage.from("printful-designs").createSignedUrl(path,3600);if(signError)throw signError;added.push({id:crypto.randomUUID(),name:file.name,url:data.signedUrl,source:"upload"})}setAssets(current=>[...current,...added]);setActiveAssetId(current=>current||added[0]?.id||"");setMessage(`${added.length} image${added.length===1?"":"s"} added to ${collectionName}.`)}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 function addImageLink(){try{const url=new URL(imageLink);if(!/^https?:$/.test(url.protocol))throw new Error();const item={id:crypto.randomUUID(),name:url.pathname.split("/").pop()||"Linked artwork",url:url.toString(),source:"link" as const};setAssets(current=>[...current,item]);setActiveAssetId(current=>current||item.id);setImageLink("");setMessage("Image link added to the collection.")}catch{setMessage("Enter a direct http or https image link.")}}
 function removeAsset(id:string){setAssets(current=>current.filter(a=>a.id!==id));if(activeAssetId===id)setActiveAssetId(assets.find(a=>a.id!==id)?.id||"");setResult(null)}
 async function generate(){if(!product||!activeAsset)return;setBusy(true);setResult(null);setMessage(`Generating ${productRole.toLowerCase()} mockup…`);try{const v=product.sync_data?.variant,catalogProductId=v?.product?.product_id,catalogVariantId=v?.product?.variant_id??v?.variant_id;if(!catalogProductId||!catalogVariantId)throw new Error("Product is missing catalog IDs. Sync it in Artisan Studio first.");const info=await callPrintful(`/mockup-generator/printfiles/${catalogProductId}`,"GET",undefined,undefined,storeId);const entry=info.variant_printfiles?.find((x:any)=>x.variant_id===catalogVariantId),printfileId=entry?.placements?.[placement],area=info.printfiles?.find((x:any)=>x.printfile_id===printfileId);if(!printfileId)throw new Error("That placement is unavailable.");const payload={variant_ids:[catalogVariantId],format:"png",files:[{placement,image_url:activeAsset.url,position:{area_width:area?.width||1800,area_height:area?.height||2400,width:area?.width||1800,height:area?.height||2400,top:0,left:0}}]};const task=await callPrintful(`/mockup-generator/create-task/${catalogProductId}`,"POST",payload,undefined,storeId);for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,3000));const poll=await callPrintful("/mockup-generator/task","GET",undefined,{task_key:task.task_key},storeId);if(poll.status==="failed")throw new Error(poll.error?.message||"Printful failed");if(["completed","done"].includes(poll.status)){const url=poll.mockups?.[0]?.mockup_url||poll.mockups?.[0]?.preview_url;if(!url)throw new Error("No mockup URL returned");setResult({url,product:product.name,placement});setMessage("Mockup ready for approval. Nothing was sent to Shopify.");return}}throw new Error("Printful timed out. Try again.")}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function approve(){if(!result||!product)return;setBusy(true);setMessage("Creating Shopify draft…");try{const variants=products.filter(p=>p.name===product.name).map(p=>{const v=p.sync_data?.variant||{};return{color:p.color,size:p.size,cost:v.retail_price??v.price??v.product?.price,sku:v.sku??v.external_id}}),draft=await createShopifyDraft({title:`${collectionName} — ${result.product}`,collection_name:collectionName,product_role:productRole,design_direction:designDirection,mockup_url:result.url,placement:result.placement,variants});setMessage(`Shopify draft created: ${draft.title}`);window.open(draft.admin_url,"_blank","noopener,noreferrer")}catch(e:any){setMessage(e.message||"Shopify draft failed")}finally{setBusy(false)}}
 if(!authReady)return <main><header><p>FRONTLINE OPERATOR</p><h1>Loading…</h1></header></main>;if(!session)return <main><header><p>FRONTLINE OPERATOR</p><h1>Operator sign in</h1><span className="bad">{message}</span></header><section><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy||!email||!password} onClick={signIn}>Sign in</button></section></main>;
 return <main><header><p>FRONTLINE OPERATOR</p><h1>Collection Builder</h1><span className={stores.length?"ok":"bad"}>{message}</span></header><nav><strong>Design Drop</strong><span>Collections</span><span>Printful</span><span>Shopify Drafts</span></nav>
 <section><h2>1. Build the product family</h2><div className="two-col"><label>Collection name<input value={collectionName} onChange={e=>setCollectionName(e.target.value)}/></label><label>Product role<select value={productRole} onChange={e=>setProductRole(e.target.value)}>{productRoles.map(role=><option key={role}>{role}</option>)}</select></label></div><label>Collection direction<textarea rows={4} value={designDirection} onChange={e=>setDesignDirection(e.target.value)}/></label><small className="hint">Use the same collection for coordinated baby, kids, mom, dad, and accessory products. Change the role before generating each item.</small></section>
 <section><h2>2. Pull in reference artwork</h2><label className="dropzone">Upload several PNG or JPG images<input type="file" multiple accept="image/png,image/jpeg" disabled={busy} onChange={e=>e.target.files&&uploadFiles(e.target.files)}/></label><div className="link-row"><input aria-label="Direct image link" placeholder="Or paste a direct image link" value={imageLink} onChange={e=>setImageLink(e.target.value)}/><button disabled={!imageLink} onClick={addImageLink}>Add link</button></div>{assets.length>0&&<div className="asset-grid">{assets.map(asset=><article className={asset.id===activeAssetId?"asset active":"asset"} key={asset.id}><button className="asset-pick" onClick={()=>{setActiveAssetId(asset.id);setResult(null)}}><img src={asset.url} alt={asset.name}/><span>{asset.name}</span><small>{asset.source}</small></button><button className="remove" aria-label={`Remove ${asset.name}`} onClick={()=>removeAsset(asset.id)}>×</button></article>)}</div>}<small className="hint">The outlined image is used for the next mockup. Add the rest of your Forging Hammahs images here as you find them.</small></section>
 <section><h2>3. Create the product mockup</h2><label>Printful store<select value={storeId||""} onChange={e=>setStoreId(Number(e.target.value))}>{stores.map(s=><option key={s.id} value={s.id}>{s.name} ({s.type})</option>)}</select></label><label>Product<select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Choose cached product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} — {[p.color,p.size].filter(Boolean).join(" / ")}</option>)}</select></label><label>Placement<select value={placement} onChange={e=>setPlacement(e.target.value)}><option value="front">Front</option><option value="back">Back</option><option value="sleeve_left">Left sleeve</option><option value="sleeve_right">Right sleeve</option></select></label><button disabled={busy||!activeAsset||!productId} onClick={generate}>{busy?"Working…":`Generate ${productRole} mockup`}</button></section>
 {result&&<section className="approval"><h2>Awaiting your approval</h2><img src={result.url}/><p><strong>{collectionName}</strong> · {productRole}<br/>{result.product} · {result.placement}</p><small>Approval creates one Shopify draft with smart pricing, collection story, sizes, colors, and this mockup. It does not publish.</small><div><a href={result.url} target="_blank">Open full size</a><button disabled={busy} onClick={approve}>{busy?"Creating draft…":"Approve & create Shopify draft"}</button><button className="reject" disabled={busy} onClick={()=>setResult(null)}>Reject</button></div></section>}</main>
}
